version: "3.8"

services:
  kommo-mcp:
    image: ghcr.io/cardosolucass96/kommo-mcp-server:latest
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MCP_PASSWORD=${MCP_PASSWORD}
    networks:
      - traefik-public
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.kommo-mcp.rule=Host(`mcp-kommo.cardosolucas.com`)"
        - "traefik.http.routers.kommo-mcp.entrypoints=websecure"
        - "traefik.http.routers.kommo-mcp.tls.certresolver=letsencrypt"
        - "traefik.http.services.kommo-mcp.loadbalancer.server.port=3000"
        - "traefik.http.services.kommo-mcp.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.kommo-mcp.loadbalancer.healthcheck.interval=30s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik-public:
    external: true
